#
# GitHub Actions workflow for building and publishing Conflux node Docker images.
#
# This workflow is manually triggered (workflow_dispatch) and allows specifying
# the upstream version, target networks, and platforms.
#
name: "Build and Publish Conflux Node Image"

on:
  workflow_dispatch:
    inputs:
      upstream_ref:
        description: "Upstream conflux-rust git tag or branch for mainnet/devnet (e.g., v3.0.1)"
        required: true
        default: "v3.0.1"
      testnet_ref:
        description: "Upstream conflux-rust git tag or branch for testnet (e.g., v3.0.1-testnet)"
        required: true
        default: "v3.0.1-testnet"
      # We target groups in the bake file (e.g., "default" or "minimal")
      targets:
        description: "Bake targets to build (e.g., 'default' for all networks)"
        required: true
        default: "default"
      platforms:
        description: "Comma-separated list of platforms to build for"
        required: true
        default: "linux/amd64,linux/arm64"
      push:
        description: "Push the image to GHCR (true/false)"
        required: true
        default: "true"

jobs:
  build-and-publish:
    name: "Build ${{ github.event.inputs.targets }} for ${{ github.event.inputs.platforms }}"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v5

      - name: "Set up QEMU for multi-architecture builds"
        uses: docker/setup-qemu-action@v3

      - name: "Set up Docker Buildx"
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: "Log in to GitHub Container Registry (GHCR)"
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: "Build and Push with Make"
        run: |
          make build \
            UPSTREAM_REF=${{ github.event.inputs.upstream_ref }} \
            TESTNET_REF=${{ github.event.inputs.testnet_ref }} \
            PUSH=${{ github.event.inputs.push }} \
            PLATFORMS=${{ github.event.inputs.platforms }} \
            TARGETS=${{ github.event.inputs.targets }} \
            BUILDX_NAME=${{ steps.buildx.outputs.name }}